name: dasShop
main: net.dasunterstrich.dasshop.DasShop
version: ${version}
api-version: '1.13'
author: 'das_'
description: Yet Another Shop Plugin

commands:
  dasshop:
    description: The main command of dasShop
    aliases:
      - das
